---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.10.1
    hooks:
      - id: ansible-lint
